language: node_js

node_js:
  - "6"

script:
  - npm run build

before_deploy:
  - rm -rf node_modules

deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-nodejs#yarn
  api_key:
    secure: nOusXJwEsR8ZuEARhk5wlygwXj2xoDSpB/9Bv41bexOvk5+lYHjNMwgd4MsHpEUHn931e5009780oNclfE4gZrlbfNRRq+HyRdfsffkKx9T1EQOGvyoGq7N8AlEaTpwyB9yTB+bnPxiVEZzwMub250/58OUZidM006ZOSB4v4VPFP3Yr5YI5Xz1o8i81iphki5S3lA72gdj9Xxsx7rTv+95I2lg8SmoAMDcUGowl/UGBZCm1k74nMyyM9JC2cjRujkvT2Rnc0wyHCU1U4sg83R9Ob4Zvteu2OrFSMLMXApa7WvMMZpdd9rkoaEujniLDjzhMnhRZhatWz6BIhE+1qnuokLPWks4sFkNBgOQZP0KD++1e81iNVQkiy2mPjMlOCwCdTnUw8ONPKSli4V4WA+zLzmfuicp5BDETk/9W5RNqxZf5+jqAOUkCj4tOeRGTu90QjoNi8fZeWzurOxxYuGQRW4IYKJpzNs2V7Nr7jU3QtPm3CpB07Coe77sPa8NsZpicSRGLtEQRpV8VCk2qLkLMnsz7Xn0eIeM8ds0lBY0uiHuJXWu3z98nw/IJDC4NbqaEnGxlOBbkWuuVUysb4KVyeeNy0xE7o7uFZWKOZWQOOf3OkWXoJJteu3ExAzA4wzNYDsytMlTWLgr56z62i98K3Iwie7lT+KSXuXkoYCA=
  app: ph-react-template
  skip_cleanup: true
